---

- hosts: webservers
  gather_facts: yes
  vars: 
     nginx_port: 8080
     root_dir: /usr/share/nginx/html
     dynamic_service_name: "{{ server_name }}"
     current_date: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"


  tasks:
    - name: Install cowsay package
      ansible.builtin.package:
        name: cowsay
        state: present
      become: yes
      tags: install-cowsay

    - name: Run cowsay command
      ansible.builtin.command: "/usr/games/cowsay 'This is server {{ server_name }}!'"
      register: cowsay_result
      become: yes
      tags: run-cowsay

    - name: Create HTML template
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: "{{ root_dir }}/index.html"
      become: yes
      when: cowsay_result is defined
      tags: create-index.html